- meta:
    id: 1
    slug: albignasego
  name: Albignasego
  subtitle: Parco bellissimo
  description: Slide-able screen tablet/phone usable wherever you go. Also really durable
- meta:
    id: 2
    slug: colle-allegro
  name: Colle Triste
  subtitle: Parco bruttissimo
  description: Digestible smart electronics that can transmitt some kind of experience or meditation to one's head