- meta:
    id: 1
    slug: albignasego
  name: Albignasego
  subtitle: Parco bellissimo
  description: Da area marginale incolta a parco pubblico che connette tessuto urbano e campagna coltivata.Il progetto del Parco della Costituzione di Albignasego, sviluppato con Mide Architetti, parte da una riflessione alla scalaterritoriale, con l’obiettivo di coniugare e trovare un equilibrio tra costruito e paesaggio, tra funzionalità e ambiente, innescando nuove connessioni.Gli elementi del paesaggio dalla forte vocazione campestre vengono reinterpretati all’interno del parco e diventano elementicaratterizzanti, memoria storica, e al contempo funzionali alle nuove attività. Una trama di percorsi secondari scandisce lasuddivisione degli spazi, assicurando la permeabilità dell’area e la connessione tra le attività, pensate per diverse tipologie diutenze e di utilizzo durante tutto il corso dell’anno.
- meta:
    id: 2
    slug: colle-allegro
  name: Colle Triste
  subtitle: Parco bruttissimo
  description: Digestible smart electronics that can transmitt some kind of experience or meditation to one's head
